### ISSUE TITLE
minor deployment guide updates

### ISSUE THREAD

**Issue by letoams** [aws-quickstart/quickstart-ec2-ipsec-mesh#4]
Hi,

Thanks for writing this guide! I am happy to see amazon integrating libreswan and specifically the mesh encryption using Opportunistic IPsec.

I only have a few minor updates for the guide :)

Current text:
config/clear should contain any networks that do not need IPsec protection. For example, these might include Amazon Route 53(DNS), Elastic Load Balancing,or Amazon RDS.

I would move this description below the other ones and clarify that this is used to create exceptions. For example if private contains 10.1.0.0/16 but you need to make an exception for 10.1.0.10/32 or 10.1.13.0/24 than those entries should be added to "clear". And particularly, 0.0.0.0/0 should NOT be added to clear, even if communication to the internet should not be using IPsec protection. Current phrasing might lead people to believe they need to add 0.0.0.0/0 to this group.

Current Text:
config/clear-or-private should contain networks with optional IPsec protection. These networks will star tclear and will then attempt to add IPsec protection.

Proposed new Text:
config/clear-or-private should contain networks which by default do not attempt to add IPsec protection when initiating IP traffic, but that should respond to other nodes requesting IPsec protection when responding to IP traffic.. This also allows a fallback to unencrypted IP traffic if the IPsec negotiation fails. 

Current Text:
config/private-or-clear should also contain networks with optional IPsec protection. However, these networks will start with IPsec protection and will then fall back to unencrypted (clear) traffic.

Proposed new Text:
config/private-or-clear should also contain networks with optional IPSec protection. However, these networks will start with IPsec protection and will allow a fallback to unencrypted (clear) traffic when the IPsec negotiation fails.

Maybe for the "private" entry, replace "require" with "mandate" to be more clear?

The guide mentions a tag "IPSec" with a capitical S instead of a lowercase s. I'm not sure if that matters.

You use the command:  sudo ipsec whack --trafficstatus which is valid, but it might be a little more userfriendly to use the command: sudo ipsec trafficstatus    (which is an alias to the above whack command)

You write:
Q: The IPsec connection is lost after a few hours and can only be established from one host (in one direction).

We have resolved a bug in upstream libreswan that could lead to connections not re-establishing properly after an hour. This fix will be released in libreswan version 3.28

You write:
A.Route 53, Amazon RDS,and other AWS managed services do not support IPsec. You need to exclude them from encryption by listing them in the config/clearlist.

I'm a little confused by this, unless those servers are part of the network ranges specified in private, private-or-clear or clear-or-private. Or if 0.0.0.0/0 is mistakenly added to one of those groups. If these services are outside of the client subnet ranges, then Opportunistic IPsec would not be attempted to those nodes.

You write:
sudo ipsec whack –debug

Note that the --debug got mangled into a special character and people can no longer copy & paste that. But also, the --debug command requires an argument, eg --debug all
But we do not recommend enabling debug at all unless you believe you are tracking a bug in the libreswan code, usually after talking to the developers on the libreswan mailing list (or on #swan irc at freenode)

Again, thanks for writing the guide and I will soon try this out myself once I brush up on my amazon knowledge!

Paul

**Comment by tzvetkov75** [comment]
Hi Paul, 
We greatly appreciate your feedback and libreswan that rocks :-) 

Here short answers:

>Current text:
>config/clear should contain any networks that do not need IPsec protection. For example, these might include Amazon Route 53(DNS), Elastic Load Balancing,or Amazon RDS.
>I would move this description below the other ones and clarify that this is used to create exceptions. For example if private contains 10.1.0.0/16 but you need to make an exception for 10.1.0.10/32 or 10.1.13.0/24 than those entries should be added to "clear". And particularly, 0.0.0.0/0 should NOT be added to clear, even if communication to the internet should not be using IPsec protection. Current phrasing might lead people to believe they need to add 0.0.0.0/0 to this group.

It makes sense, we will improve next iteration

>Current Text:
>config/clear-or-private should contain networks with optional IPsec protection. These networks will start clear and will then attempt to add IPsec protection.
>Proposed new Text:
>config/clear-or-private should contain networks which by default do not attempt to add IPsec protection when initiating IP traffic, but that should respond to other nodes requesting IPsec protection when responding to IP traffic. This also allows a fallback to unencrypted IP traffic if the IPsec negotiation fails.

I agree, we will clarify it 

>Current Text:
>config/private-or-clear should also contain networks with optional IPsec protection. However, these networks will start with IPsec protection and will then fall back to unencrypted (clear) traffic.
>Proposed new Text:
>config/private-or-clear should also contain networks with optional IPSec protection. However, these networks will start with IPsec protection and will allow a fallback to unencrypted (clear) traffic when the IPsec negotiation fails.

I agree 

>You use the command: sudo ipsec whack --trafficstatus which is valid, but it might be a little more userfriendly to use the command: sudo ipsec trafficstatus (which is an alias to the above whack command

Ok, we will discuss to integrate it 
 
>You write:
>Q: The IPsec connection is lost after a few hours and can only be established from one host (in one direction).
>We have resolved a bug in upstream libreswan that could lead to connections not re-establishing properly after an hour. This fix will be released in libreswan version 3.28

This is referring to AWS Security Groups that are stateful firewall, that may block IKE initiation depending on the direction. Thanks for the v3.28 hint.

>You write:
>A.Route 53, Amazon RDS,and other AWS managed services do not support IPsec. You need to exclude them from encryption by listing them in the config/clearlist.
>I'm a little confused by this, unless those servers are part of the network ranges specified in >private, private-or-clear or clear-or-private. 
Your first suggestion: for example DNS Service (Route 53) has IP (.2) from network range in private config

>You write:
>sudo ipsec whack –debug
>Note that the --debug got mangled into a special character and people can no longer copy & paste that. But also, the --debug command requires an argument, eg --debug all
But we do not recommend enabling debug at all unless you believe you are tracking a bug in the libreswan code, usually after talking to the developers on the libreswan mailing list (or on #swan irc at freenode)

 ok, we will make it clearer in the next in interaction

Thanks again!

Vesselin

**Comment by tzvetkov75** [comment]
Hi Paul, 

we updated the documentation including your comments. 

Many thanks!
 
Vesselin
