### ISSUE TITLE
mixed use of IPsec and IPSec 

### ISSUE THREAD

**Issue by antonyantony** [aws-quickstart/quickstart-ec2-ipsec-mesh#5]
I am very happy to see the document and try it. Great job!

Using IPsec would be better, consistent with RFC. I noticed IPSec and IPsec are in use in the document 
Is the  tag "IPSec" is that case sensitive? 

RF 4301
"The spelling "IPsec" is preferred and used throughout this and all  related IPsec standards.  All other capitalizations of IPsec (e.g., IPSEC, IPSec, ipsec) are deprecated."

**Comment by vsnyc** [comment]
Thanks Antony for the note, in the [documentation](https://aws-quickstart.s3.amazonaws.com/quickstart-ec2-ipsec-mesh/doc/libreswan-ipsec-mesh-on-the-aws-cloud.pdf) we have used `IPsec` throughout. The only place `IPSec` is used is on the tags, changing that will unfortunately require a code change.

**Comment by antonyantony** [comment]
thanks for the response. I understand, once it is n the code it could be hard to change.
