### ISSUE TITLE
SSM does not seems to initialize

### ISSUE THREAD

**Issue by antonyantony** [aws-quickstart/quickstart-ec2-ipsec-mesh#6]
I am following the quickstart guide and noticed the tag IPSec do not change to enabled. IPSec:todo

Now I am using  Amazon Linux 2 instance. Looking in the instance I see. 
 ssm-cli  get-instance-information
2019/05/15 05:56:20 Failed to load instance info from vault. RegistrationKey does not exist.
{"instance-id":"i-0adcb22c4511e1a6a","region":"us-east-2","release-version":"2.3.372.0"} 

I am trying to figure out how to configure ssm.
 
PS: this is my first time using AWS EC2.

**Comment by antonyantony** [comment]
I think I found the log "/aws/lambda/IPSecSetup-IPsec-mesh"  is this a failure or a success?
It didn't copy files or install libresawn, I am wondering if this is the cause?

Instance is in VPC vpc-6a041d02 but operation restricted via params to VPC libreswan-01 Exit
END RequestId: 923ddec5-be00- 

I ama still not srue SSM end point is right.

**Comment by tzvetkov75** [comment]
Thanks Antony, you need restrict the operation to vpc-id, thus vpc-6a041d02 (not the name libreswan-01) or leave it default to 'any' meaning all vpcs in your account. After you finish stop and than start the instance again.

**Comment by antonyantony** [comment]
thanks @tzvetkov75 tunnel up and working.  This is great!
ipsec  whack --trafficstatus
006 #2: "private#172.31.0.0/16"[1] ...172.31.24.146, type=ESP, add_time=1557943233, inBytes=704, outBytes=704, id='CN=ip-172-31-24-146.us-east-2.compute.internal'
