### ISSUE TITLE
can't delete stack, may be because I created more than one

### ISSUE THREAD

**Issue by antonyantony** [aws-quickstart/quickstart-ec2-ipsec-mesh#8]
I created multiple stacks using the same url and different names. Now I can't delete them. May the CA is shared ?

04 Jun 2019 11:20:48 | IPsec-mesh |  
The following resource(s) failed to delete: [CaBucket]. 

04 Jun 2019 11:20:47 | CaBucket |  
The bucket you tried to delete is not empty (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; Request ID: 1C8237822FFD42AE; S3 Extended Request ID: Dbf3xiRkYXfC0JFB1720G3X+H+sZSpskNhFjIBgSWIDj0vdrNBwFgsqSootJ08cYo9mZRPt8bmI)

**Comment by antonyantony** [comment]
It seems I have to delete many resources manually. Also noticed the host certificates has to deleted manually. then I can delete. May be this is the only way to delete the stack?

**Comment by vsnyc** [comment]
Yes, you can delete the S3 buckets first and then delete the stack. Since the bucket contains private keys and certificates, we have chosen to not automatically delete the bucket when the stack is deleted.

We'll add a FAQ for this.

**Comment by antonyantony** [comment]
thanks for the clarification. It make sense to leave the CAcert and cleanup explicitly.

I noticed the host certificate stay after an instance is terminated. Would it be re-used?  
The s3 bucket seems to grow.
Also wondered if that would affect the cost. I am playing with free tier t2.mico , still getting charged for some s3 services. Yet to figure exactly what I am charged for..
